# Custom Language File for Launcher Customizer

[ejs.app]
title = "MyungJiDae Launcher"

[ejs.landing]
mediaHomeURL = "#"
mediaLinkURL = "#"
mediaMapURL = "#"
mediaGitHubURL = "https://github.com/minjunkim0205/Development-MyungJiDaeCustomClient"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "https://github.com/minjunkim0205/Development-MyungJiDaeCustomClient"
supportLink = "#"

[ejs.welcome]
welcomeHeader = "MyungJiDae Launcher"
welcomeDescription = "명지우의 대단한 서버"
welcomeDescCTA = "@Jiwoo @Minjun @Geonhee"
